#!/bin/zsh

# This needs to be set in order for autocomplete to work on run shortcut
export PATH="$HOME/bin:$PATH"

# Setup Monitor
xrandr --dpi 144 --output eDP1 --auto
dispwin ~/.config/colors/laptop.icc
xrdb -merge ~/.Xresources

# blank screen after 10 minutes
xset s 600 600

# Setup Wallpaper
nitrogen --restore &

# Start Programs
clipster -d &
start-pulseaudio-x11 &
udiskie &
unclutter &
dunst &
dropbox &
blueman-applet &

# Start Screensaver
xautolock -time 7 -locker "glitchlock" -corners --00  -cornerdelay 4 -cornerredelay 4 -detectsleep &

# enable ctrl-alt-backspace
setxkbmap -option terminate:ctrl_alt_bksp
# Setup keyboard
xmodmap ~/.Xmodmap
xcape -e 'Control_R=Escape;Super_R=Tab'

# Speed up touchpad a little
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Speed" .3

# This is needed for mutt
export GPG_AGENT_INFO="${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent"
echo "UPDATESTARTUPTTY" | gpg-connect-agent

# Start policy kit
/usr/lib/polkit-1/polkitd --no-debug

# Start awesome
exec i3
