#!/bin/zsh

# This needs to be set in order for autocomplete to work on run shortcut
export PATH="$HOME/bin:$PATH"

# Setup Monitor
#if [ "$(xrandr | grep 'DP3 connected')" ] ; then
    # DPI for this monitor is actually 109, but that makes the fonts too small
#    xrandr --dpi 125 --output DP3 --auto --output LVDS1 --off
#    dispwin -d1 ~/.config/colors/desktop.icc
#    xrdb -merge ~/.Xresources27
#else
    # Internal Monitor
    xrandr --dpi 125 --output LVDS1 --auto --output DP3 --off
    dispwin ~/.config/colors/laptop.icc
    xrdb -merge ~/.Xresources
#fi

# Start recoll
#/usr/share/recoll/examples/rclmon.sh start

# Start Programs
anamnesis --start &
xscreensaver -no-splash &
start-pulseaudio-x11 & 
udiskie &
dropbox &
unclutter &
nm-applet &
blueman-applet &
autokey-gtk &

# enable ctrl-alt-backspace
setxkbmap -option terminate:ctrl_alt_bksp
# Setup keyboard
xmodmap ~/.Xmodmap
xcape -e 'Control_R=Escape'

# Setup ssh-agent for all connections
eval $(ssh-agent)

# Setup gpg agent for all connections
envfile="$HOME/.gnupg/gpg-agent.env"
if [[ -e "$envfile" ]] && kill -0 $(grep GPG_AGENT_INFO "$envfile" | cut -d: -f 2) 2>/dev/null; then
    eval "$(cat "$envfile")"
else
    eval "$(gpg-agent --daemon --write-env-file "$envfile")"
fi
# This is needed for mutt
export GPG_AGENT_INFO=$HOME/.gnupg/S.gpg-agent

# Start policy kit
/usr/lib/polkit-1/polkitd --no-debug

# Infinality Setup
#export INFINALITY_FT_FILTER_PARAMS="07 24 35 24 07"
#export INFINALITY_FT_FRINGE_FILTER_STRENGTH="60"
#export INFINALITY_FT_USE_VARIOUS_TWEAKS="true"
#export INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH="20"
export INFINALITY_FT="ultimate4"

# Start loop for checking email if file exists
if [[ -h ~/bin/loopmbsync.sh ]]; then
    ~/bin/loopmbsync.sh &
fi

# Start awesome
exec awesome
