#!/bin/zsh

# This needs to be set in order for autocomplete to work on run shortcut
export PATH="$HOME/bin:$PATH"

# Setup Monitor
#if [ "$(xrandr | grep 'DP3 connected')" ] ; then
    # DPI for this monitor is actually 109, but that makes the fonts too small
#    xrandr --dpi 125 --output DP3 --auto --output LVDS1 --off
#    dispwin -d1 ~/.config/colors/desktop.icc
#    xrdb -merge ~/.Xresources27
#else
    # Internal Monitor
    xrandr --dpi 144 --output eDP1 --auto
    dispwin ~/.config/colors/laptop.icc
    xrdb -merge ~/.Xresources
#fi

# blank screen after 10 minutes
xset s 600 600

# Setup Wallpaper
nitrogen --restore &

# Start Programs
clipster -d &
start-pulseaudio-x11 &
udiskie &
unclutter &
nm-applet &
#blueman-applet &
autokey-gtk &
dunst &
#redshift-gtk &

# Start Screensaver
xautolock -time 7 -locker "glitchlock" -corners --00  -cornerdelay 4 -cornerredelay 4 &

# enable ctrl-alt-backspace
setxkbmap -option terminate:ctrl_alt_bksp
# Setup keyboard
xmodmap ~/.Xmodmap
xcape -e 'Control_R=Escape;Super_R=Tab'

# Disable touchpad on Thinkpad
xinput set-prop 'TPPS/2 Elan TrackPoint' 'libinput Accel Speed' .9
xinput set-prop 'TPPS/2 Elan TrackPoint' 'libinput Accel Profile Enabled' 0, 1

# This is needed for mutt
export GPG_AGENT_INFO="${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent"
echo "UPDATESTARTUPTTY" | gpg-connect-agent

# Start policy kit
/usr/lib/polkit-1/polkitd --no-debug

# Start awesome
exec i3
