fpath=("$HOME/.zsh/prompt" $fpath)
autoload -Uz async
autoload -U promptinit
async
promptinit


SPACESHIP_PROMPT_ORDER=(
  dir
  git_branch
  git_status
#  kubecontext
#  azure
  exec_time
  line_sep
  jobs
  char
)

SPACESHIP_RPROMPT_ORDER=(
  time
)

# time
SPACESHIP_TIME_FORMAT="%D{%L:%M}"
SPACESHIP_TIME_SHOW=true

# dir
SPACESHIP_DIR_PREFIX=''
SPACESHIP_DIR_TRUNC='5'
SPACESHIP_DIR_TRUNC_PREFIX=".../"
SPACESHIP_DIR_TRUNC_REPO=false

# git
SPACESHIP_GIT_BRANCH_PREFIX=""
#SPACESHIP_GIT_BRANCH_SUFFIX=""
SPACESHIP_GIT_STATUS_PREFIX="["
SPACESHIP_GIT_STATUS_SUFFIX="]"
SPACESHIP_GIT_STATUS_UNTRACKED="?"
SPACESHIP_GIT_STATUS_ADDED="+"
SPACESHIP_GIT_STATUS_MODIFIED="!"
SPACESHIP_GIT_STATUS_RENAMED="»"
SPACESHIP_GIT_STATUS_DELETED="✘"
SPACESHIP_GIT_STATUS_STASHED="$"
SPACESHIP_GIT_STATUS_UNMERGED="="
SPACESHIP_GIT_STATUS_AHEAD="⇡"
SPACESHIP_GIT_STATUS_BEHIND="⇣"
SPACESHIP_GIT_STATUS_DIVERGED="⇕"

# kubecontext
SPACESHIP_KUBECONTEXT_PREFIX=""
#SPACESHIP_KUBECONTEXT_SUFFIX=""
export SPACESHIP_KUBECONTEXT_COLOR_GROUPS=(
 red -prod-
)

# symbols
SPACESHIP_CHAR_SYMBOL="❯ "
SPACESHIP_JOBS_SYMBOL="»"

prompt spaceship
