#!/bin/zsh

# Install zplug if it doesn't exist
if [ ! -d "$HOME/.zplug" ]; then
  curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
fi



# Source each file ending in .zsh in the .zsh directory
for script in ~/.zsh/*.zsh; do
  source "$script"
done

# Plugins
source ~/.zplug/init.zsh

zplug "zsh-users/zsh-history-substring-search"
zplug mafredri/zsh-async, from:github
zplug intelfx/pure, use:pure.zsh, from:github, as:theme
zplug "Tarrasch/zsh-bd"
zplug "zdharma/fast-syntax-highlighting"

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load
