#!/bin/zsh

# Install zplug if it doesn't exist
if [ ! -d "$HOME/.zplug" ]; then
  curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
fi

# Plugins
source ~/.zplug/init.zsh

# My zsh dotfiles
setopt +o nomatch
if stat --printf='' /etc/*release 2>/dev/null >/dev/null; then
  if grep -q "Arch Linux" /etc/*release; then
    zplug "soleblaze/dotfiles", use:"zsh/{*.zsh,os/archlinux.zsh,other/gpg.zsh}"
  elif grep -q "Ubuntu" /etc/*release; then
    zplug "soleblaze/dotfiles", use:"zsh/{*.zsh,os/ubuntu.zsh,other/homelab.zsh}"
  elif grep -q "Debian" /etc/*release; then
    zplug "soleblaze/dotfiles", use:"zsh/{*.zsh,os/ubuntu.zsh}"
  fi
else
  zplug "soleblaze/dotfiles", use:"zsh/{*.zsh,os/macos.zsh,other/gpg.zsh}"
fi
setopt -o nomatch


# Other zsh plugins
zplug "MichaelAquilina/zsh-you-should-use"
zplug "hlissner/zsh-autopair", defer:2
zplug "rupa/z", use:z.sh
zplug "changyuheng/fz", defer:1
zplug "zdharma/fast-syntax-highlighting", defer:2
zplug "zsh-users/zsh-history-substring-search"

# Competions
zplug 'g-plane/zsh-yarn-autocompletions'
zplug 'srijanshetty/zsh-pip-completion'
zplug 'zsh-users/zsh-completions'
zplug 'ttscoff/doing', use:doing.completion.zsh

# prompt
zplug romkatv/powerlevel10k, as:theme, depth:1

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load

# Source local zshrc if it exists
if [ -f "$HOME/.zshrc_local" ]; then
  source "$HOME/.zshrc_local"
fi
