#!/bin/bash

cpuusage="$(mpstat 1 1 | tail -n1 | awk '{printf "%.1f%%", 100 - $12}')"
zone="thermal_zone1"
temp="$(awk '{printf "%2dC", $1/1000}' /sys/class/thermal/$zone/temp)"

if [[ "$temp" ]]; then
    echo "<span foreground='#0088ff'>  </span><span foreground='#bbbbbb'>$cpuusage ($temp)</span>"
else
    echo "<span foreground='#0088ff'>  </span><span foreground='#bbbbbb'>$cpuusage</span>"
fi
