#!/bin/bash

cpuusage="$(mpstat 1 1 | tail -n1 | awk '{printf "%.1f%%", 100 - $12}')"
temp="$(sensors | grep Package | awk '{print $4}' | tr -d '°+')"

if [[ "$temp" ]]; then
    echo "<span foreground='#0088ff'>  </span><span foreground='#bbbbbb'>$cpuusage ($temp)</span>"
else
    echo "<span foreground='#0088ff'>  </span><span foreground='#bbbbbb'>$cpuusage</span>"
fi
