#!/bin/bash
doinglast=$(grep -A1 "Currently:" ~/.config/doing/doing.md | tail -n1 | sed 's/.*|\ *//')


if echo "$doinglast" | grep -qv '@done'; then
  echo "<span foreground='#ffffff' background='#808080'>  </span><span foreground='#ffffff' background='#1478db'> $doinglast </span>"
fi

case $BLOCK_BUTTON in
  1) notify-send doing "$doinglast" ;;
esac
