#!/bin/bash

mboxpath=~/.mail

count="$(for i in ${mboxpath}/*/Inbox/new; do ls "$i"; done | wc -l)"

if [[ "$count" -ne 0 ]]; then
    echo "<span foreground='#0088ff'> </span><span foreground='#bbbbbb'>$count</span>"
fi
