#!/bin/bash

mboxpath=~/.mail

count="$(for i in ${mboxpath}/*/Inbox/new; do ls "$i"; done | wc -l)"

if [[ "$count" -ne 0 ]]; then
    echo "<span foreground='#ffffff' background='#808080'>  </span><span foreground='#ffffff' background='#1478db'> $count </span>"
fi
