#!/bin/env bash

memorypercentage="$(free -m | grep Mem| awk '{printf "%.1f%%", $3/$2*100}')"

echo "<span foreground='#ffffff' background='#808080'>  </span><span foreground='#ffffff' background='#1478db'> $memorypercentage </span>"
