#!/bin/bash

case $BLOCK_BUTTON in
  1)
    mpdstatus="$(mpc next)"
    title="$(echo "$mpdstatus" | head -n 1)"
    icon
    title
    ;;
  2)
    mpdstatus="$(mpc toggle)"
    title="$(echo "$mpdstatus" | head -n 1)"
    icon
    title
    ;;
  3)
    mpdstatus="$(mpc prev)"
    title="$(echo "$mpdstatus" | head -n 1)"
    icon
    title
    ;;
esac

#      
# Validate mpd is running
icon() {
  if echo "$mpdstatus" | grep -q "\[playing\]"; then
    icon=""
  elif echo "$mpdstatus" | grep -q "\[paused\]"; then
    icon=""
  else
    echo
    exit
  fi
}

# Update
mpdstatus="$(mpc status)"
title="$(mpc current -f '[%artist% - ]%title%')"

output() {
  echo "<span foreground='#ffffff' background='#808080'> $icon </span><span foreground='#ffffff' background='#1478db'> $title </span>"
}

icon
output
